set_property SRC_FILE_INFO {cfile:d:/Computer_system/nscscc2022_group_qualifier_submission/nscscc2022_group_qualifier_submission/release_project/func_test_v0.01/soc_sram_func/rtl/xilinx_ip/clk_pll/clk_pll.xdc rfile:../../../../../../../rtl/xilinx_ip/clk_pll/clk_pll.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Computer_system/nscscc2022_group_qualifier_submission/nscscc2022_group_qualifier_submission/release_project/func_test_v0.01/soc_sram_func/run_vivado/mycpu_prj1/mycpu.runs/clk_pll_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk_in1 [get_ports clk_in1]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PHASESHIFT_MODE WAVEFORM [get_cells plle2_adv_inst]
current_instance
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clkfbout_clk_pll -source [get_pins inst/plle2_adv_inst/CLKIN1] -multiply_by 1 -add -master_clock [get_clocks clk_in1] [get_pins inst/plle2_adv_inst/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name cpu_clk_clk_pll -source [get_pins inst/plle2_adv_inst/CLKIN1] -edges {1 2 3} -edge_shift {0.000 5.000 10.000} -add -master_clock [get_clocks clk_in1] [get_pins inst/plle2_adv_inst/CLKOUT0]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name timer_clk_clk_pll -source [get_pins inst/plle2_adv_inst/CLKIN1] -multiply_by 1 -add -master_clock [get_clocks clk_in1] [get_pins inst/plle2_adv_inst/CLKOUT1]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells inst]
